In [3]:
number = input()
#> ? 6
type(number)

str

In [8]:

dictionary = {
    'REG': 'regg',
    'log': 'AAAogeee',
    'cart': 'SXNAUIWC'
}

# Accessing the value associated with the key 'log'
value = dictionary['log']
print(value)

dictionary['log']

AAAogeee


'AAAogeee'

In [10]:
def calc(wage, hours):
    print(wage * hours)

calc(10, 40)-200

400


TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'

In [12]:
students = ["Denise", "Arsen", "Tony", "Audrey"]
low = lambda x: x[0].lower()

print(list(map(low, students)))

['d', 'a', 't', 'a']


In [14]:
names = {"Denise": "French", "Jean":"French",
         "John": "American", "Sarah": "American"}
new_names = ["FR_" + name if names[name]=="French" else "US_" + name for name in names.keys()]

new_names

['FR_Denise', 'FR_Jean', 'US_John', 'US_Sarah']

In [16]:
def sqr_root(x):
    """Calculate the square root of the input x"""
    sqr_r = x ** (1/2)

sqr_root(16)

In [17]:
names = ["Denise", "Arsen", "Tony", "Audrey"]
ages = [25, 30, 27, 20]
cities = ["Paris", "Lyon", "Paris", "Marseille"]

list(zip(names, ages, cities))

[('Denise', 25, 'Paris'),
 ('Arsen', 30, 'Lyon'),
 ('Tony', 27, 'Paris'),
 ('Audrey', 20, 'Marseille')]

In [20]:
import numpy as np
from functools import reduce

num_list = np.arange(10)

filter_list = list(filter(lambda x: x % 3 == 0, num_list))

final_list = reduce(lambda x, y: x * y, filter_list)

final_list

0

In [28]:
import numpy as np
serie = np.arange(1, 10)
print(serie)
x = [3, 4, 5]
serie[x]

print(serie)
print(serie[x])

[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[4 5 6]


In [ ]:
import seaborn as sns

titanic = sns.load_dataset('titanic')
sns.countplot(x='class', data=titanic)

plt.show()